// Code generated by go generate ; DO NOT EDIT.

package example


func (p *Station) GetExp() int {
    return p.Exp
}

func (p *Station) SetExp(value int) {
    p.Exp = value
}

func (p *Station) GetName() string {
    return p.Name
}

func (p *Station) SetName(value string) {
    p.Name = value
}

